version: "3"
services:
  gophish:
    build: ./gophish
    ports: 
      - 3333:3333
      - 8080:8080
      - 8443:8443
      - 80:80
    volumes:
      - shared:/opt/db:rw

  evilginx3:
    build: ./evilginx3
    stdin_open: true
    tty: true
    depends_on:
      - gophish
    ports: 
      - 443:443
      - 53:53
    extra_hosts:
      - "localhost:127.0.0.1"
      - "sub.localtest.com:127.0.0.1"
    volumes:
      - shared:/opt/db:rw

volumes:
  shared:
    name: shared